name = "MassGap"
moreLeanArgs = ["-Dprofiler=true", "-Dprofiler.threshold=1000"]
defaultTargets = ["MassGap", "MassGapChecks"]
testDriver = "MassGapChecks"

[[lean_lib]]
name = "MassGap"

[[lean_lib]]
name = "MassGapChecks"

[lean_lib.leanOptions]
Elab.async = false

[leanOptions]
warningAsError = true
